### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by ugintl** [tangram/autolink_filter#1]
I am not able to understand its use. I am already using search auto complete module. Is it a filter which I can use in a text format for autocomplete? I need the later.

Is it on drupal?

**Comment by tangram** [comment]
Yes, it's a text formatting filter for Drupal 7.
1. Checkout the repo. 
2. Copy JS and CSS files from https://github.com/betamos/Better-Autocomplete to this folder as per the instructions (you can minify `jquery.better-autocomplete.js` or just rename it to `jquery.better-autocomplete.min.js`). 
3. Copy project folder to your `modules` folder.
4. Activate from your modules screen.
5. Activate the filter in one of your text formats.

I'm sorry, it's been 4 years since I wrote it and used it. I don't know if it still works, there may have been changes in Drupal or dependencies. I can try to give more support if needed.

**Comment by ugintl** [comment]
Thank u for a quick reply. I will use it and let you know

**Comment by ugintl** [comment]
Not working. This will be a great thing to have. Does it also show user pictures? If you know about statuses module, it has a submodule named status tags and status tag suggestions which converts @ and # into links with auto suggest, but it restricted to only posts. It not even works on status comments. And it conflicts with some modules as well. I am using mentions module for this.

**Comment by ugintl** [comment]
I have a request if u can. I want to have a filter which, when I paste a link in text area, it generates a preview and when I click the link, if it is a video, it should play it on my site in an embedded player. I am using statuses module 7.x-1.x-dev for status updates and opengraph filter 7.x-1.0-beta1 module to generate preview of links shared in status posts, but when i click it takes me to the link page. There is a module video filter, it does what I want, but it has 2 problems. 1. It requires user to use [video:URLhere] this format. 2. It does not retrieve details. I would be greatful if you can be of any help.

**Comment by tangram** [comment]
Hi, I had another look at the filter. While it does seem to work with `@user` (no, it doesn't show user pictures), at least for me and according to the instructions I posted, I see that the code is not generalized for nodes, it searches for hard-coded categories. It also has hard-coded Norwegian text.

I do not recommend using this at all, and I will not develop it further, as I don't work with Drupal anymore. It is very likely there is something better in the Drupal ecosystem. Thanks for your interest.
